services:
  db:
    build: .
    container_name: netra_postgis
    environment:
      POSTGRES_USER: netra_user
      POSTGRES_PASSWORD: netra_password
      POSTGRES_DB: netra_cctv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: